import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import Layout from '../components/Layout'



export default function Home() {
  
 const [data, setData] = useState([])
 const [query, setQuery] = useState("")
 const [search, setSearch] = useState("")
 const [isLoading, setIsLoading] = useState(false)

 useEffect(() => {
    const fetchData = async () => {
      const resp = await fetch(`https://api.unsplash.com/search/photos?page=1&client_id=UvS4jl6oDd8OdU-b15ZKJgtGVHKYOuDUx7W_9d5GKTU&query=${query}`)
      const data = await resp.json()
      setData(data.results)
      setIsLoading(false)
    };
    fetchData()
}, [search])
  

  const handleChange = e => {
    e.preventDefault()
    setQuery(e.target.value)
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    setSearch(query)
  }



  return (

    <Layout>
      <Head>
        <title>Test Programacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <div className="container mt-5 col-4">
          <form className="container" onSubmit={handleSubmit}>
            <div className="row">
              <input 
              className="form-control col" 
              type="text" 
              placeholder="Type something..."
              autoComplete="off" 
              name="title"
              value={query}
              onChange={handleChange}
              aria-label="default input example"/>
            </div>
            <div className="row">
              <button type="submit" className="btn btn-primary mt-3 col ">Search</button>
            </div>

            
          </form>
        </div>
     
  <div className="container d-flex flex-wrap mt-3">
  {isLoading ? (
        <h5>Loading ...</h5>
      ) :
         data.map(({id, urls, alt_description}) => (
           
           <div className="m-2" key={id}>
            <Image 
             src={urls.regular}
             alt={alt_description}
            width={400}
            height={400}/>
            </div>
            
         ))
       }
  </div>
      

      </main>

      
    </Layout>
  )
}

